"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-16

Creates the three tables that make up the whole schema, per
docs/DATABASE.md: destinations, venues, and publish_revisions.
Hand-written (not autogenerated) — there's no reachable database in this
environment to autogenerate against, and for a three-table schema this is
easy to keep in exact sync with app/db/models.py by hand.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DESTINATION_STATUSES = ("draft", "review", "approved", "archived")
VENUE_STATUSES = ("draft", "review", "approved", "archived")
VENUE_CATEGORIES = (
    "Restaurant",
    "Cafe",
    "Hotel",
    "Beach",
    "Nightlife",
    "Shopping",
    "Services",
    "Entertainment",
    "Other",
)


def upgrade() -> None:
    op.create_table(
        "destinations",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("region", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("boundary", postgresql.JSONB(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(f"status IN {DESTINATION_STATUSES}", name="ck_destinations_status"),
    )

    op.create_table(
        "venues",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("destination_id", sa.Text(), nullable=False),
        sa.Column("district", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("latitude", sa.Numeric(9, 6), nullable=True),
        sa.Column("longitude", sa.Numeric(9, 6), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("whatsapp", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("maps_url", sa.Text(), nullable=True),
        sa.Column("instagram_handle", sa.Text(), nullable=True),
        sa.Column("facebook_handle", sa.Text(), nullable=True),
        sa.Column("tiktok_handle", sa.Text(), nullable=True),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("cover_image_url", sa.Text(), nullable=True),
        sa.Column("gallery_image_urls", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("opening_hours", postgresql.JSONB(), nullable=True),
        sa.Column("beach_details", postgresql.JSONB(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("last_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["destination_id"], ["destinations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("destination_id", "slug", name="uq_venues_destination_id_slug"),
        sa.CheckConstraint(f"status IN {VENUE_STATUSES}", name="ck_venues_status"),
        sa.CheckConstraint(f"category IN {VENUE_CATEGORIES}", name="ck_venues_category"),
    )
    op.create_index(op.f("ix_venues_destination_id"), "venues", ["destination_id"])

    op.create_table(
        "publish_revisions",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("snapshot", postgresql.JSONB(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "published_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("published_by", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("destination_count", sa.Integer(), nullable=True),
        sa.Column("venue_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_publish_revisions_is_current",
        "publish_revisions",
        ["is_current"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )


def downgrade() -> None:
    op.drop_table("publish_revisions")
    op.drop_index(op.f("ix_venues_destination_id"), table_name="venues")
    op.drop_table("venues")
    op.drop_table("destinations")
